import { semantic } from './semantic'

export const mapped = {
  button: {
    primary: {
      background:      semantic.color.brand.default,
      backgroundHover: semantic.color.brand.hover,
      backgroundActive:semantic.color.brand.active,
      text:            semantic.color.text.inverse,
      border:          semantic.color.brand.default,
      radius:          semantic.radius.component,
    },
    secondary: {
      background:      semantic.color.background.surface,
      backgroundHover: semantic.color.background.subtle,
      text:            semantic.color.text.default,
      border:          semantic.color.border.default,
      radius:          semantic.radius.component,
    },
    ghost: {
      background:      'transparent',
      backgroundHover: semantic.color.background.subtle,
      text:            semantic.color.text.secondary,
      border:          'transparent',
      radius:          semantic.radius.component,
    },
    destructive: {
      background:      semantic.color.status.error,
      backgroundHover: semantic.color.brand.hover,
      text:            semantic.color.text.inverse,
      border:          semantic.color.status.error,
      radius:          semantic.radius.component,
    },
  },
  card: {
    background: semantic.color.background.surface,
    border:     semantic.color.border.default,
    radius:     semantic.radius.card,
    padding:    semantic.space.component.lg,
    shadow:     semantic.shadow.card,
    shadowHover:semantic.shadow.cardHover,
  },
  input: {
    background:   semantic.color.background.surface,
    border:       semantic.color.border.default,
    borderFocus:  semantic.color.border.focus,
    borderHover:  semantic.color.border.strong,
    text:         semantic.color.text.default,
    placeholder:  semantic.color.text.muted,
    radius:       semantic.radius.component,
  },
  tag: {
    background: semantic.color.brand.subtle,
    text:       semantic.color.text.brand,
    border:     semantic.color.brand.muted,
    radius:     semantic.radius.tag,
    fontSize:   semantic.font.size.label,
    fontWeight: semantic.font.weight.medium,
  },
  avatar: {
    radius:   semantic.radius.pill,
    fontSize: semantic.font.size.caption,
    fontWeight: semantic.font.weight.semibold,
  },
  sidebar: {
    background:      semantic.color.background.surface,
    border:          semantic.color.border.default,
    itemDefault:     'transparent',
    itemHover:       semantic.color.background.subtle,
    itemActive:      semantic.color.brand.subtle,
    itemActiveText:  semantic.color.text.brand,
    itemText:        semantic.color.text.secondary,
    width:           '220px',
  },
  modal: {
    background: semantic.color.background.surface,
    border:     semantic.color.border.default,
    radius:     semantic.radius.modal,
    shadow:     semantic.shadow.modal,
    overlay:    'rgba(26, 21, 20, 0.4)',
  },
  postCard: {
    background:      semantic.color.background.surface,
    border:          semantic.color.border.default,
    borderHover:     semantic.color.border.strong,
    radius:          semantic.radius.card,
    padding:         semantic.space.component.lg,
    shadow:          semantic.shadow.card,
    shadowHover:     semantic.shadow.cardHover,
    authorName:      semantic.color.text.default,
    authorMeta:      semantic.color.text.secondary,
    content:         semantic.color.text.default,
    timestamp:       semantic.color.text.muted,
    actionText:      semantic.color.text.muted,
    actionHover:     semantic.color.text.brand,
  },
  aiCard: {
    background:      semantic.color.brand.subtle,
    border:          semantic.color.brand.muted,
    radius:          semantic.radius.card,
    padding:         semantic.space.component.lg,
    labelText:       semantic.color.text.brand,
    contentText:     semantic.color.text.default,
  },
  jobCard: {
    background:      semantic.color.background.surface,
    border:          semantic.color.border.default,
    radius:          semantic.radius.card,
    padding:         semantic.space.component.lg,
    shadow:          semantic.shadow.card,
    shadowHover:     semantic.shadow.cardHover,
    companyText:     semantic.color.text.secondary,
    roleText:        semantic.color.text.default,
    matchBadgeBg:    semantic.color.brand.subtle,
    matchBadgeText:  semantic.color.text.brand,
  },
  chatBubble: {
    sent: {
      background: semantic.color.brand.default,
      text:       semantic.color.text.inverse,
      radius:     semantic.radius.card,
    },
    received: {
      background: semantic.color.background.subtle,
      text:       semantic.color.text.default,
      radius:     semantic.radius.card,
    },
  },
} as const